# Make sure it says jdbc:postgresql and NOT jdbc:mysql
spring.datasource.url=jdbc:postgresql://localhost:5432/Shop
spring.datasource.username=postgres
spring.datasource.password=atharv

# Force Spring to use the Postgres driver
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true